name: hello
on:
  push:
    branches:
      - main
jobs:
  greets:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: merging the code
        run: echo "Hello from github actions"
        
