name: Portfolio
on:
    push:
        branches: 
            - main
    workflow_dispatch:
        
jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu:latest
        steps: 
            - name: code checkout
              uses: action/checkout@v4

            - name: Configure GitHub Pages
              uses: actions/configure-pages@v4
            
            - name: Upload static files as artifact
              uses: actions/upload-pages-artifact@v3 

            - name: deploy the static website
              uses: actions/deploy-pages@v4